on: [push]
jobs:
  import_areas:
    runs-on: ubuntu-latest
    name: Import Areas
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install babashka
        uses: just-sultanov/setup-babashka@v2
        with:
            version: '1.3.191'

      - name: Import Areas
        run: bb areas

      - name: Commit files
        run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add data/AddressGeneral/getAreas.xml
            git commit -a -m "Update getAreas.xml"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}