on:
  schedule:
    # every 15 days
    - cron: "0 10 */10 * *"

jobs:
  import_cities:
    runs-on: ubuntu-latest
    name: Import Settlements
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install babashka
        uses: just-sultanov/setup-babashka@v2
        with:
          version: '1.3.191'
      
      - name: git config
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: bb streets
        run: |
           bb streets
           git add data/AddressGeneral/getStreet.xml
           git commit -a -m "Update getStreet.xml"

      - name: check if changes
        run: |
          git diff  --quiet && echo "Nothing changes" && exit 0;

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true